import type { Promotion } from "./types";

/** Circular week: Thursday Sep 3 – Wednesday Sep 9, 2026 (today is Mon Sep 7). */
export const WEEK_START = "2026-09-03";
export const WEEK_END = "2026-09-09";
export const WEEK_LABEL = "Sep 3–9, 2026";
export const TODAY = "2026-09-07";
export const EXPIRY_ALERT_BY = "2026-09-10";

export const PROMOTIONS: Promotion[] = [
  // Publix BOGO week
  {
    id: "pub-straw-bogo",
    productId: "strawberries",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 5.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Buy one 1 lb clamshell, get one free. Effective $3.00 each when you take both.",
  },
  {
    id: "pub-blue-bogo",
    productId: "blueberries",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 5.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "18 oz blueberries BOGO. Best if you actually need two.",
  },
  {
    id: "pub-pasta-bogo",
    productId: "spaghetti",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 1.79,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Barilla 16 oz pasta, BOGO.",
  },
  {
    id: "pub-prego-bogo",
    productId: "marinara",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 2.49,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Prego 24 oz, BOGO.",
  },
  {
    id: "pub-bacon-bogo",
    productId: "bacon",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 6.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Oscar Mayer 12 oz bacon, BOGO. Beats everyday Walmart if you freeze the extra.",
  },
  {
    id: "pub-dogs-bogo",
    productId: "hot-dogs",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 4.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Ball Park beef franks, BOGO.",
  },
  {
    id: "pub-chips-bogo",
    productId: "chips",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 4.49,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Lay's 7.75 oz, BOGO.",
  },
  {
    id: "pub-coke-bogo",
    productId: "coke-12",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 7.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Coca-Cola 12-pack cans, BOGO. Limit 2 offers.",
  },
  {
    id: "pub-bounty-bogo",
    productId: "paper-towels",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 14.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Bounty 6 mega rolls, BOGO. Huge if you have storage.",
  },
  {
    id: "pub-charmin-bogo",
    productId: "toilet-paper",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 15.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Charmin 12 mega rolls, BOGO.",
  },
  {
    id: "pub-philly-bogo",
    productId: "cream-cheese",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 2.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Philadelphia 8 oz, BOGO.",
  },
  {
    id: "pub-chobani-bogo",
    productId: "greek-yogurt",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 5.49,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Chobani 32 oz, BOGO.",
  },
  {
    id: "pub-bagels-bogo",
    productId: "bagels",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 3.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Thomas' bagels, BOGO.",
  },
  {
    id: "pub-pizza-bogo",
    productId: "frozen-pizza",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 6.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "DiGiorno rising crust, BOGO.",
  },
  {
    id: "pub-cheerios-bogo",
    productId: "cheerios",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 4.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Cheerios 18 oz, BOGO.",
  },
  {
    id: "pub-folgers-bogo",
    productId: "coffee",
    storeId: "publix",
    kind: "bogo",
    label: "BOGO",
    salePrice: 9.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Folgers 30.5 oz, BOGO.",
  },
  {
    id: "pub-chicken-sale",
    productId: "chicken-breast",
    storeId: "publix",
    kind: "sale",
    label: "This week",
    salePrice: 1.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Pub Sub week adjacent: boneless breast $1.99/lb. Rare Publix meat win.",
  },

  // Walmart rollbacks
  {
    id: "wmt-eggs",
    productId: "eggs",
    storeId: "walmart",
    kind: "rollback",
    label: "Rollback",
    salePrice: 2.22,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Large eggs dozen rollback at the US-1 Supercenter.",
  },
  {
    id: "wmt-beef",
    productId: "ground-beef",
    storeId: "walmart",
    kind: "rollback",
    label: "Rollback",
    salePrice: 3.97,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "80/20 ground beef rollback, per lb.",
  },
  {
    id: "wmt-chicken",
    productId: "chicken-breast",
    storeId: "walmart",
    kind: "rollback",
    label: "Rollback",
    salePrice: 1.97,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Boneless skinless breast rollback. Watch package dates.",
  },
  {
    id: "wmt-milk",
    productId: "whole-milk",
    storeId: "walmart",
    kind: "rollback",
    label: "Rollback",
    salePrice: 2.92,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Great Value whole gallon.",
  },
  {
    id: "wmt-detergent",
    productId: "detergent",
    storeId: "walmart",
    kind: "rollback",
    label: "Rollback",
    salePrice: 7.94,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Tide 92 oz liquid rollback.",
  },
  {
    id: "wmt-water",
    productId: "water-24",
    storeId: "walmart",
    kind: "sale",
    label: "Rollback",
    salePrice: 2.88,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "24-pack purified water.",
  },
  {
    id: "wmt-bananas",
    productId: "bananas",
    storeId: "walmart",
    kind: "rollback",
    label: "Rollback",
    salePrice: 0.48,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Bananas per lb at the Supercenter.",
  },
  {
    id: "wmt-spaghetti",
    productId: "spaghetti",
    storeId: "walmart",
    kind: "rollback",
    label: "Rollback",
    salePrice: 0.88,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Great Value spaghetti 16 oz.",
  },
  {
    id: "wmt-cheerios",
    productId: "cheerios",
    storeId: "walmart",
    kind: "rollback",
    label: "Rollback",
    salePrice: 3.24,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Cheerios 18 oz rollback.",
  },

  // Target Circle
  {
    id: "tgt-avocado-circle",
    productId: "avocados",
    storeId: "target",
    kind: "circle",
    label: "Circle 30% off",
    salePrice: 0.9,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Good & Gather avocados, 30% off with Circle. Clip in the Target app.",
    requiresClip: true,
  },
  {
    id: "tgt-yogurt-dotw",
    productId: "greek-yogurt",
    storeId: "target",
    kind: "circle",
    label: "Deal of the week",
    salePrice: 3.49,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Good & Gather 32 oz Greek yogurt. Circle members.",
    requiresClip: true,
  },
  {
    id: "tgt-berries",
    productId: "frozen-berries",
    storeId: "target",
    kind: "bogo50",
    label: "BOGO 50% off",
    salePrice: 3.19,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Good & Gather frozen mixed berries, second bag half off.",
  },
  {
    id: "tgt-cheerios-coupon",
    productId: "cheerios",
    storeId: "target",
    kind: "coupon",
    label: "$1 Circle coupon",
    couponValue: 1,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "$1 off Cheerios 18 oz, clip once.",
    requiresClip: true,
  },
  {
    id: "tgt-laundry",
    productId: "detergent",
    storeId: "target",
    kind: "circle",
    label: "Circle $3 off",
    couponValue: 3,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "$3 off Tide 92 oz with Circle.",
    requiresClip: true,
  },
  {
    id: "tgt-pizza",
    productId: "frozen-pizza",
    storeId: "target",
    kind: "sale",
    label: "Weekly",
    salePrice: 3.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "DiGiorno rising crust weekly ad.",
  },

  // Aldi produce + finds
  {
    id: "aldi-straw",
    productId: "strawberries",
    storeId: "aldi",
    kind: "sale",
    label: "Produce special",
    salePrice: 1.69,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "1 lb strawberries. Best produce buy in St. Augustine this week.",
  },
  {
    id: "aldi-avo",
    productId: "avocados",
    storeId: "aldi",
    kind: "sale",
    label: "2 for $1.50",
    salePrice: 0.75,
    minQty: 2,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Hass avocados 2 for $1.50. Single still $0.79.",
  },
  {
    id: "aldi-grapes",
    productId: "grapes",
    storeId: "aldi",
    kind: "sale",
    label: "Produce special",
    salePrice: 1.29,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Red seedless grapes per lb.",
  },
  {
    id: "aldi-blue",
    productId: "blueberries",
    storeId: "aldi",
    kind: "sale",
    label: "Produce special",
    salePrice: 2.89,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "18 oz blueberries.",
  },
  {
    id: "aldi-chicken",
    productId: "chicken-breast",
    storeId: "aldi",
    kind: "aldi-finds",
    label: "Fresh special",
    salePrice: 2.19,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Never Frozen chicken breast per lb. Check the case early.",
  },
  {
    id: "aldi-eggs",
    productId: "eggs",
    storeId: "aldi",
    kind: "sale",
    label: "Weekly",
    salePrice: 1.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Dozen large eggs.",
  },
  {
    id: "aldi-rotisserie",
    productId: "rotisserie",
    storeId: "aldi",
    kind: "aldi-finds",
    label: "Fresh",
    salePrice: 4.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Seasoned rotisserie chicken, while they last.",
  },
  {
    id: "aldi-bananas",
    productId: "bananas",
    storeId: "aldi",
    kind: "sale",
    label: "Everyday low",
    salePrice: 0.39,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Bananas per lb. Bring a bag.",
  },
  {
    id: "pub-pb-coupon",
    productId: "peanut-butter",
    storeId: "publix",
    kind: "coupon",
    label: "Digital $1 off",
    couponValue: 1,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Publix app coupon on Jif 16 oz. Clip before checkout.",
    requiresClip: true,
  },
  {
    id: "pub-deli-sale",
    productId: "deli-turkey",
    storeId: "publix",
    kind: "sale",
    label: "Deli special",
    salePrice: 5.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Boar's Head-style oven roasted turkey, this week only.",
  },
  {
    id: "wmt-bananas",
    productId: "bananas",
    storeId: "walmart",
    kind: "rollback",
    label: "Unadvertised",
    salePrice: 0.48,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "US-1 Supercenter produce wall. Still behind Aldi.",
  },
  {
    id: "tgt-bounty",
    productId: "paper-towels",
    storeId: "target",
    kind: "circle",
    label: "Circle $4 off",
    couponValue: 4,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "$4 off Bounty 6 mega with Circle. Publix BOGO still wins if you take two.",
    requiresClip: true,
  },
  {
    id: "aldi-peaches",
    productId: "peaches",
    storeId: "aldi",
    kind: "sale",
    label: "Produce special",
    salePrice: 0.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Yellow peaches per lb. Seasonal Florida window.",
  },
  {
    id: "aldi-kale",
    productId: "kale",
    storeId: "aldi",
    kind: "sale",
    label: "Produce special",
    salePrice: 1.29,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Bunch kale.",
  },

  // Winn-Dixie A1A
  {
    id: "wd-straw",
    productId: "strawberries",
    storeId: "winndixie",
    kind: "sale",
    label: "Weekly",
    salePrice: 2.49,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "1 lb strawberries on the A1A ad. Still behind Aldi.",
  },
  {
    id: "wd-chicken",
    productId: "chicken-breast",
    storeId: "winndixie",
    kind: "sale",
    label: "Meat special",
    salePrice: 2.29,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Boneless breast per lb. Beats everyday Publix, loses to Walmart rollback.",
  },
  {
    id: "wd-beer",
    productId: "beer-12",
    storeId: "winndixie",
    kind: "sale",
    label: "12-pack special",
    salePrice: 11.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Miller Lite 12-pack at the island Winn-Dixie.",
  },

  // CVS ExtraBucks-style
  {
    id: "cvs-toothpaste",
    productId: "toothpaste",
    storeId: "cvs",
    kind: "bogo",
    label: "BOGO",
    salePrice: 4.79,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Crest 5.8 oz BOGO. ExtraBucks after if you spend $20 on beauty.",
  },
  {
    id: "cvs-shampoo",
    productId: "shampoo",
    storeId: "cvs",
    kind: "coupon",
    label: "$3 ExtraBucks",
    couponValue: 3,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "$3 ExtraBucks on Pantene 12.6 oz. Clip in the CVS app.",
    requiresClip: true,
  },
  {
    id: "cvs-body",
    productId: "body-wash",
    storeId: "cvs",
    kind: "sale",
    label: "Weekly",
    salePrice: 5.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Dove body wash weekly.",
  },

  // Walgreens
  {
    id: "wg-deo",
    productId: "deodorant",
    storeId: "walgreens",
    kind: "bogo",
    label: "BOGO",
    salePrice: 6.49,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Old Spice BOGO at the A1A Walgreens.",
  },
  {
    id: "wg-toothpaste",
    productId: "toothpaste",
    storeId: "walgreens",
    kind: "bogo50",
    label: "BOGO 50% off",
    salePrice: 4.49,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Crest second tube half off.",
  },
  {
    id: "wg-lotion",
    productId: "lotion",
    storeId: "walgreens",
    kind: "sale",
    label: "Rewards",
    salePrice: 4.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Lubriderm 16.9 oz with myWalgreens.",
  },

  // ABC Fine Wine
  {
    id: "abc-vodka",
    productId: "vodka-175",
    storeId: "abc",
    kind: "sale",
    label: "Spirits special",
    salePrice: 22.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Tito's 1.75 L at ABC on A1A. Best nearby spirit price unless you drive to Costco.",
  },
  {
    id: "abc-wine",
    productId: "wine-chard",
    storeId: "abc",
    kind: "sale",
    label: "Wine sale",
    salePrice: 8.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Kendall-Jackson Chardonnay 750 ml.",
  },
  {
    id: "abc-seltzer",
    productId: "seltzer-12",
    storeId: "abc",
    kind: "sale",
    label: "12-pack",
    salePrice: 13.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "White Claw 12-pack.",
  },

  // Costco bulk (only ranks if you turn on far clubs)
  {
    id: "costco-chicken",
    productId: "chicken-breast",
    storeId: "costco",
    kind: "sale",
    label: "Kirkland tray",
    salePrice: 2.49,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Kirkland boneless tray, per lb equivalent. 19 miles from 32080.",
  },
  {
    id: "costco-paper",
    productId: "paper-towels",
    storeId: "costco",
    kind: "sale",
    label: "Kirkland 12-pack",
    salePrice: 5.89,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Warehouse pack priced per 6-roll equivalent. Storage required.",
  },
  {
    id: "costco-vodka",
    productId: "vodka-175",
    storeId: "costco",
    kind: "sale",
    label: "Kirkland / Tito's",
    salePrice: 19.99,
    startsOn: WEEK_START,
    endsOn: WEEK_END,
    details: "Cheapest 1.75 in the market if you already have a membership and the drive.",
  },
];

export const PROMO_MAP: Record<string, Promotion> = Object.fromEntries(
  PROMOTIONS.map((p) => [p.id, p]),
);

export function promosForProduct(productId: string, storeId?: string): Promotion[] {
  return PROMOTIONS.filter(
    (p) => p.productId === productId && (!storeId || p.storeId === storeId),
  );
}

export function promosForStore(storeId: string): Promotion[] {
  return PROMOTIONS.filter((p) => p.storeId === storeId);
}

export function isPromoActive(promo: Promotion, on = new Date()): boolean {
  const t = on.toISOString().slice(0, 10);
  return t >= promo.startsOn && t <= promo.endsOn;
}
