import { MARKET_ZIP, type Store, type StoreId, type StoreKind } from "./types";

export const STORE_KIND_LABEL: Record<StoreKind, string> = {
  grocery: "Grocery",
  pharmacy: "Pharmacy",
  dollar: "Dollar",
  liquor: "Wine & spirits",
  convenience: "C-store",
  club: "Warehouse club",
  farm: "Farms & markets",
};

export const STORES: Store[] = [
  {
    id: "publix",
    name: "Publix",
    short: "Publix",
    kind: "grocery",
    tagline: "The 32080 store is Anastasia Plaza — BOGO week is where the math flips.",
    hours: "Daily 7:00am–10:00pm · Liquors 9am–9pm (Sun 1–8pm)",
    miles: 1,
    zip: "32080",
    sells: "Full grocery, pharmacy, beer & wine, attached Publix Liquors for spirits",
    locations: [
      {
        name: "Anastasia Plaza",
        address: "1033 A1A Beach Blvd",
        city: "St. Augustine Beach",
        zip: "32080",
      },
      {
        name: "Publix Liquors",
        address: "1031 A1A Beach Blvd",
        city: "St. Augustine Beach",
        zip: "32080",
      },
      {
        name: "Cobblestone Village",
        address: "125 Jenkins St",
        city: "St. Augustine",
        zip: "32086",
      },
      {
        name: "US-1 South",
        address: "4255 US Highway 1 S",
        city: "St. Augustine",
        zip: "32086",
      },
      {
        name: "Shoppes at Mission Trace",
        address: "955 State Road 16",
        city: "St. Augustine",
        zip: "32084",
      },
    ],
  },
  {
    id: "winndixie",
    name: "Winn-Dixie",
    short: "Winn-Dixie",
    kind: "grocery",
    tagline: "Right on A1A South — the other full grocer on the island, with a liquor store next door.",
    hours: "Daily 7:00am–10:00pm",
    miles: 3,
    zip: "32080",
    sells: "Full grocery, pharmacy, beer & wine, Winn-Dixie Liquor for spirits",
    locations: [
      {
        name: "A1A South",
        address: "3905 A1A S",
        city: "St. Augustine Beach",
        zip: "32080",
      },
      {
        name: "Winn-Dixie Liquor",
        address: "3907 A1A S",
        city: "St. Augustine Beach",
        zip: "32080",
      },
      {
        name: "Ponce South",
        address: "1010 S Ponce De Leon Blvd",
        city: "St. Augustine",
        zip: "32084",
      },
      {
        name: "Ponce North",
        address: "3551 N Ponce De Leon Blvd",
        city: "St. Augustine",
        zip: "32084",
      },
    ],
  },
  {
    id: "aldi",
    name: "Aldi",
    short: "Aldi",
    kind: "grocery",
    tagline: "Produce and staples, lowest everyday prices — a short hop over the bridge.",
    hours: "Daily 8:30am–8:00pm (Blackford Way 9am–8pm)",
    miles: 7,
    zip: "32084",
    sells: "Grocery, produce, household, personal care, beer & wine. Bring a quarter for the cart.",
    locations: [
      {
        name: "US-1 South",
        address: "1773 US Hwy 1 S",
        city: "St. Augustine",
        zip: "32084",
      },
      {
        name: "Shores Village",
        address: "181 Blackford Way",
        city: "St. Augustine",
        zip: "32086",
      },
    ],
  },
  {
    id: "walmart",
    name: "Walmart Supercenter",
    short: "Walmart",
    kind: "grocery",
    tagline:
      "The one Supercenter in town — same shelf prices for pickup and Walmart+. Sam's Club is the warehouse cousin, 38 miles out.",
    hours: "Daily 6:00am–11:00pm",
    miles: 8,
    zip: "32086",
    sells: "Full grocery, pharmacy, household, personal care, beer & wine. Walmart+ ships 32080 from this store.",
    locations: [
      {
        name: "US-1 Supercenter #579",
        address: "2355 US Highway 1 S",
        city: "St. Augustine",
        zip: "32086",
      },
      {
        name: "Saint Johns Supercenter",
        address: "845 Durbin Pavilion Dr",
        city: "Saint Johns",
        zip: "32259",
      },
    ],
  },
  {
    id: "target",
    name: "Target",
    short: "Target",
    kind: "grocery",
    tagline: "Circle offers on grocery, household, and personal care.",
    hours: "Daily 8:00am–10:00pm",
    miles: 6,
    zip: "32084",
    sells: "Grocery, household, personal care, pharmacy, beer & wine",
    locations: [
      {
        name: "US-1 South",
        address: "1440 US Hwy 1 S",
        city: "St. Augustine",
        zip: "32084",
      },
    ],
  },
  {
    id: "cvs",
    name: "CVS",
    short: "CVS",
    kind: "pharmacy",
    tagline: "Two on the island — ExtraBucks on soap, shampoo, and toothpaste.",
    hours: "Daily 8:00am–10:00pm (pharmacy hours shorter)",
    miles: 2,
    zip: "32080",
    sells: "Pharmacy, personal care, household, snacks, drinks, limited dairy",
    locations: [
      {
        name: "A1A South",
        address: "1920 A1A S",
        city: "St. Augustine Beach",
        zip: "32080",
      },
      {
        name: "SR 312",
        address: "175 SR 312 W",
        city: "St. Augustine",
        zip: "32080",
      },
    ],
  },
  {
    id: "walgreens",
    name: "Walgreens",
    short: "Walgreens",
    kind: "pharmacy",
    tagline: "On A1A South past Winn-Dixie — BOGOs on personal care beat grocery some weeks.",
    hours: "Daily 8:00am–10:00pm",
    miles: 3.5,
    zip: "32080",
    sells: "Pharmacy, personal care, household, snacks, drinks, limited dairy",
    locations: [
      {
        name: "A1A South",
        address: "3975 A1A S",
        city: "St. Augustine Beach",
        zip: "32080",
      },
      {
        name: "US-1 South",
        address: "2075 US Hwy 1 S",
        city: "St. Augustine",
        zip: "32086",
      },
    ],
  },
  {
    id: "dollargeneral",
    name: "Dollar General",
    short: "DG",
    kind: "dollar",
    tagline: "Two on Anastasia Island. Spices, soap, and pantry fillers without crossing the bridge.",
    hours: "Daily 8:00am–10:00pm",
    miles: 2,
    zip: "32080",
    sells: "Pantry, spices, personal care, household, snacks, drinks",
    locations: [
      {
        name: "A1A South",
        address: "1953 A1A S",
        city: "St. Augustine Beach",
        zip: "32080",
      },
      {
        name: "Crescent Beach",
        address: "5575 A1A S Ste 105",
        city: "St. Augustine",
        zip: "32080",
      },
    ],
  },
  {
    id: "dollartree",
    name: "Dollar Tree",
    short: "Dollar Tree",
    kind: "dollar",
    tagline: "Everything $1.25 — spices, soap, pasta, and party snacks. The big one is on US-1.",
    hours: "Daily 9:00am–9:00pm",
    miles: 8,
    zip: "32086",
    sells: "Spices, personal care, small pantry, household odds",
    locations: [
      {
        name: "US-1 South",
        address: "1938 US-1",
        city: "St. Augustine",
        zip: "32086",
      },
      {
        name: "SR 16",
        address: "500 FL-16",
        city: "St. Augustine",
        zip: "32084",
      },
    ],
  },
  {
    id: "abc",
    name: "ABC Fine Wine & Spirits",
    short: "ABC",
    kind: "liquor",
    tagline: "Best everyday spirits price on A1A — beer, wine, and the 1.75s.",
    hours: "Mon–Sat 9:00am–10:00pm · Sun 11:00am–8:00pm",
    miles: 1.5,
    zip: "32080",
    sells: "Beer, wine, liquor, mixers — Florida package store",
    locations: [
      {
        name: "A1A South",
        address: "1830 A1A S",
        city: "St. Augustine Beach",
        zip: "32080",
      },
    ],
  },
  {
    id: "cstore",
    name: "7-Eleven / Circle K",
    short: "C-store",
    kind: "convenience",
    tagline: "Open when everything else is dark. Milk, beer, bread — you pay for being close.",
    hours: "Open 24 hours",
    miles: 1,
    zip: "32080",
    sells: "Drinks, beer & wine, snacks, milk, eggs, bread, emergency soap",
    locations: [
      {
        name: "7-Eleven A1A South",
        address: "2010 A1A S",
        city: "St. Augustine Beach",
        zip: "32080",
      },
      {
        name: "Circle K Beach Blvd",
        address: "351 A1A Beach Blvd",
        city: "St. Augustine Beach",
        zip: "32080",
      },
    ],
  },
  {
    id: "costco",
    name: "Costco",
    short: "Costco",
    kind: "club",
    tagline: "World Golf Village warehouse. Bulk wins on paper, detergent, and meat — 19 miles from the beach.",
    hours: "Mon–Fri 10:00am–8:30pm · Sat 9:30am–7:00pm · Sun 10:00am–6:00pm",
    miles: 19,
    far: true,
    membership: true,
    bulk: true,
    zip: "32092",
    sells: "Bulk grocery, household, personal care, Kirkland spirits, pharmacy, gas",
    locations: [
      {
        name: "St. Augustine warehouse",
        address: "215 World Commerce Pkwy",
        city: "St. Augustine",
        zip: "32092",
      },
    ],
  },
  {
    id: "sams",
    name: "Sam's Club",
    short: "Sam's",
    kind: "club",
    tagline:
      "Walmart's warehouse cousin. Jacksonville Beach Blvd — too far for a weekly shop, right for a bulk stock-up or Instacart when clubs are on.",
    hours: "Mon–Sat 10:00am–8:00pm · Sun 10:00am–6:00pm",
    miles: 38,
    far: true,
    membership: true,
    bulk: true,
    zip: "32246",
    sells: "Bulk grocery, household, personal care, Member's Mark spirits",
    locations: [
      {
        name: "Jacksonville Beach Blvd",
        address: "10690 Beach Blvd",
        city: "Jacksonville",
        zip: "32246",
      },
    ],
  },
  {
    id: "pier",
    name: "Wednesday Pier Farmers Market",
    short: "Pier market",
    kind: "farm",
    tagline: "On the 32080 pier every Wednesday — farm produce, bread, and makers a walk from the beach.",
    hours: "Wed 8:00am–12:00pm (winter until 1:00pm)",
    miles: 1.5,
    zip: "32080",
    sells: "Farm produce, bread, eggs, honey, local makers",
    locations: [
      {
        name: "St. Johns County Ocean Pier",
        address: "350 A1A Beach Blvd",
        city: "St. Augustine Beach",
        zip: "32080",
      },
    ],
  },
  {
    id: "amphitheatre",
    name: "Amphitheatre Farmers Market",
    short: "Amphitheatre",
    kind: "farm",
    tagline: "Saturday staple on A1A South. Organic produce, local shrimp, eggs, cheese, Bee Hill honey.",
    hours: "Sat 8:30am–12:30pm (dark the 2nd Sat in May)",
    miles: 3,
    zip: "32080",
    sells: "Organic produce, eggs, cheese, shrimp, honey, baked goods",
    locations: [
      {
        name: "St. Augustine Amphitheatre",
        address: "1340C A1A S",
        city: "St. Augustine",
        zip: "32080",
      },
    ],
  },
  {
    id: "sunday-mkt",
    name: "St. Augustine Sunday Farmers Market",
    short: "Sunday market",
    kind: "farm",
    tagline: "Classic Car Museum on US-1 — pesticide-free produce, eggs, meat, baked goods. Pet-friendly.",
    hours: "Sun 9:00am–1:00pm",
    miles: 8,
    zip: "32086",
    sells: "Local produce, eggs, beef, chicken, pork, baked goods",
    locations: [
      {
        name: "Classic Car Museum",
        address: "4730 US Highway 1 S",
        city: "St. Augustine",
        zip: "32086",
      },
    ],
  },
  {
    id: "schooner",
    name: "North City Farmers Market",
    short: "Schooner's",
    kind: "farm",
    tagline: "Sundays at Schooner's — Florida-farmed produce, Bee Hill, Sunrise Brew.",
    hours: "Sun 9:00am–1:00pm",
    miles: 8,
    zip: "32084",
    sells: "Florida produce, honey, coffee, plants, makers",
    locations: [
      {
        name: "Schooner's Seafood House",
        address: "3560 N Ponce de Leon Blvd",
        city: "St. Augustine",
        zip: "32084",
      },
    ],
  },
  {
    id: "bee-hill",
    name: "Bee Hill Farm",
    short: "Bee Hill",
    kind: "farm",
    tagline: "Elkton greens, salad mix, and wildflower honey. Also at the Amphitheatre on Saturdays.",
    hours: "Seasonal farm stand · Amphitheatre Sat 8:30am–12:30pm",
    miles: 12,
    zip: "32033",
    sells: "Salad mix, lettuce, honey, beeswax, cut flowers",
    locations: [
      {
        name: "Bee Hill Farm",
        address: "Elkton",
        city: "Elkton",
        zip: "32033",
      },
    ],
  },
  {
    id: "wesley",
    name: "Wesley Wells Farms",
    short: "Wesley Wells",
    kind: "farm",
    tagline: "Fourth-generation u-pick — veggies, flowers, meats. Pumpkin Festival late September.",
    hours: "Weekend u-pick · check the farm before you drive",
    miles: 16,
    far: true,
    seasonal: true,
    zip: "32145",
    sells: "U-pick vegetables, flowers, farm meats",
    locations: [
      {
        name: "Wesley Wells Farms",
        address: "Hastings area",
        city: "Hastings",
        zip: "32145",
      },
    ],
  },
  {
    id: "county-line",
    name: "County Line Produce",
    short: "County Line",
    kind: "farm",
    tagline: "Hastings stand since the 1960s — Sebago potatoes, corn, cabbage, watermelon. Season is roughly Thanksgiving through May.",
    hours: "In season daily 8:00am–6:00pm",
    miles: 20,
    far: true,
    seasonal: true,
    zip: "32145",
    sells: "Local potatoes, corn, cabbage, peppers, watermelon, fruit",
    locations: [
      {
        name: "County Line Produce",
        address: "9260 SR 207",
        city: "Hastings",
        zip: "32145",
      },
    ],
  },
  {
    id: "springs",
    name: "Natural Springs Dairy",
    short: "Springs Dairy",
    kind: "farm",
    tagline: "Hastings farm store six days a week — milk, and a booth at the weekly market.",
    hours: "Farm store 6 days · home drop one day",
    miles: 20,
    far: true,
    zip: "32145",
    sells: "Farm milk, dairy",
    locations: [
      {
        name: "Natural Springs Dairy",
        address: "8290 Smith Road",
        city: "Hastings",
        zip: "32145",
      },
    ],
  },
];

export const STORE_MAP: Record<StoreId, Store> = Object.fromEntries(
  STORES.map((s) => [s.id, s]),
) as Record<StoreId, Store>;

export const LOCALS = [
  {
    name: "Discount Groceries and More",
    kind: "Local grocer",
    address: "2185 A1A S",
    city: `St. Augustine Beach, ${MARKET_ZIP}`,
    note: "Independent discount grocer on the island. Not on the chain price book — still worth a look.",
  },
  {
    name: "Hagan Ace Hardware of Anastasia",
    kind: "Hardware",
    address: "3033 A1A S",
    city: `St. Augustine, ${MARKET_ZIP}`,
    note: "Home supplies, cleaners, and outdoor — not food.",
  },
  {
    name: "Family Dollar",
    kind: "Dollar",
    address: "2485 S US Highway 1",
    city: "St. Augustine, 32086",
    note: "Mainland dollar store. Island coverage is Dollar General.",
  },
];

export function nearbyStoreIds(): StoreId[] {
  return STORES.filter((s) => !s.far && s.kind !== "convenience").map((s) => s.id);
}
