/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ListRouteImport } from './routes/list'
import { Route as LogRouteImport } from './routes/log'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as StoresRouteImport } from './routes/stores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deals': typeof DealsRoute
  '/list': typeof ListRoute
  '/log': typeof LogRoute
  '/pantry': typeof PantryRoute
  '/prices': typeof PricesRoute
  '/scan': typeof ScanRoute
  '/stores': typeof StoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deals': typeof DealsRoute
  '/list': typeof ListRoute
  '/log': typeof LogRoute
  '/pantry': typeof PantryRoute
  '/prices': typeof PricesRoute
  '/scan': typeof ScanRoute
  '/stores': typeof StoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deals': typeof DealsRoute
  '/list': typeof ListRoute
  '/log': typeof LogRoute
  '/pantry': typeof PantryRoute
  '/prices': typeof PricesRoute
  '/scan': typeof ScanRoute
  '/stores': typeof StoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deals'
    | '/list'
    | '/log'
    | '/pantry'
    | '/prices'
    | '/scan'
    | '/stores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deals'
    | '/list'
    | '/log'
    | '/pantry'
    | '/prices'
    | '/scan'
    | '/stores'
  id:
    | '__root__'
    | '/'
    | '/deals'
    | '/list'
    | '/log'
    | '/pantry'
    | '/prices'
    | '/scan'
    | '/stores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DealsRoute: typeof DealsRoute
  ListRoute: typeof ListRoute
  LogRoute: typeof LogRoute
  PantryRoute: typeof PantryRoute
  PricesRoute: typeof PricesRoute
  ScanRoute: typeof ScanRoute
  StoresRoute: typeof StoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DealsRoute: DealsRoute,
  ListRoute: ListRoute,
  LogRoute: LogRoute,
  PantryRoute: PantryRoute,
  PricesRoute: PricesRoute,
  ScanRoute: ScanRoute,
  StoresRoute: StoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
